<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en-AU">
  <head>
    <meta http-equiv="content-type" content="application/xhtml+xml; charset=UTF-8" />
    <meta name="author" content="haran" />
    <meta name="generator" content="haran" />

    <!-- Navigational metadata for large websites (an accessibility feature): -->
    <link rel="top"      href="./index.shtml" title="Homepage" />
    <link rel="up"       href="./index.shtml" title="Up" />
    <link rel="first"    href="./index.shtml" title="First page" />
    <link rel="previous" href="./index.shtml" title="Previous page" />
    <link rel="next"     href="./index.shtml" title="Next page" />
    <link rel="last"     href="./index.shtml" title="Last page" />
    <link rel="toc"      href="./index.shtml" title="Table of contents" />
    <link rel="index"    href="./index.shtml" title="Site map" />

    <link rel="stylesheet" type="text/css" href="./gila-screen.css" media="screen" title="Main" />
    <link rel="stylesheet" type="text/css" href="./gila-print.css" media="screen" title="Print" />
    <link rel="stylesheet" type="text/css" href="./gila-print.css" media="print" title="Print" />

    <title>Codehack</title>
  </head>

  <body>
    <!-- For non-visual user agents: -->
      <div id="top"><a href="#main-copy" class="doNotDisplay doNotPrint">Skip to main content.</a></div>

    <!-- ##### Header ##### -->

    <div id="header">
      <h1 class="headerTitle">
        <a href="./index.shtml" title="Browse to homepage">Codehack 
        <span>Programming Contest Control System</span></a>
      </h1>

      <div class="subHeader">
        <span class="doNotDisplay">Navigation: </span>
        <a href="./index.shtml">Home</a> |
        <a href="./screenshots.shtml">Screenshots</a> |
        <a href="./index.shtml">Documentation</a> |
        <a href="mailto:sridhar@users.berlios.de">Contact</a>
      </div>
    </div>

    <div id="side-bar">

      <!-- ##### Left Sidebar ##### -->

      <div class="leftSideBar">
        <p class="sideBarTitle">This Page</p>
        <ul>
          <li><a href="#introduction">Introduction</a></li>
          <li><a href="#development" title="Development information">Development</a></li>
        </ul>

        <p class="sideBarTitle">Exits</p>
        <ul>
          <li><a href="http://cs.annauniv.edu/~rsridhar">Author's Home</a></li>
          <li><a href="http://debian.org">Debian GNU/Linux</a></li>
          <li><a href="http://acmicpc.org">ACM ICPC</a></li>
          <li><span class="thisPage" title="That's this page!">Codehack</span></li>
        </ul>

        <p class="sideBarTitle">Comments</p>
        <span class="sideBarText">
          Comments and constructive criticisms are welcome
          <a href="mailto:sridhar@users.berlios.de" title="Email form">via email</a>.
        </span>
      </div>

      <!-- ##### Right Sidebar ##### -->

      <div class="rightSideBar">
        <p class="sideBarTitle">News</p>
        <div class="sideBarText"><strong>11 Nov 04</strong><br />
          Screenshots are available now!</div>

        <div class="sideBarText"><strong>22 Oct 04</strong><br />
          Uploaded codehack website</div>

        <div class="sideBarText"><strong>21 Oct 04</strong><br />
          codehack now uses <a href="http://svn.berlios.de/viewcvs/codehack/trunk/">subversion</a></div>

        <a class="more">more news &raquo;</a>

        <p class="sideBarTitle">Downloads</p>

        <div class="sideBarText"><strong>Source</strong><br />
          <a href="http://developer.berlios.de/project/showfiles.php?group_id=2434">download</a></div>
        <div class="sideBarText"><strong>RPM</strong><br />
          <a href="./index.shtml">download</a></div>
        <div class="sideBarText"><strong>Debian</strong><br />
          <a href="./index.shtml">download</a></div>
        <div class="sideBarText"><strong>Windows Client</strong><br />
          <a href="./index.shtml">download</a></div>

        <p class="sideBarTitle">Validation</p>

        <div class="sideBarText">Validate the <a href="http://validator.w3.org/check/referer">XHTML</a>
          and <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> of this page.</div>
      </div>

    </div>

    <!-- ##### Main Copy ##### -->

